pipeline {
      agent any
      environment {
        MYSQL_PWD = "mydemoscret" 
        //SERVERPLATFORM = "Centos" // This is just an example.
        LS = "${sh(script:'ls -lah', returnStdout: true).trim()}"
        gitCommit = "${sh(returnStdout: true, script: 'git rev-parse HEAD').trim()}"
        // short SHA, possibly better for chat notifications, etc.
        shortCommit = "${gitCommit.take(6)}"
        }
       
      options {
            timestamps()
            ansiColor('xterm')
        }
    
    /*Clean before checkout removes the files created as part of build - say your test results etc - resets the files if they 
    were updated & pulls the latest changes if they have been updated. 
    This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory.*/
    
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        choice(name: 'SERVERPLATFORM', choices: ['Centos', 'Ubuntu'], description: 'Pick the environment to run')
        }
    
  stages {
        stage('BuildInfo') {
                steps {
                    echo "Running Buid num: ${env.BUILD_ID} on Jenkins ${env.JENKINS_URL}"
                    echo "BUILD_NUMBER :: ${env.BUILD_NUMBER}"
                    echo "BUILD_ID :: ${env.BUILD_ID}"
                    echo "BUILD_DISPLAY_NAME :: ${env.BUILD_DISPLAY_NAME}"
                    echo "JOB_NAME :: ${env.JOB_NAME}"
                    echo "JOB_BASE_NAME :: ${env.JOB_BASE_NAME}"
                    echo "BUILD_TAG :: ${env.BUILD_TAG}"
                    echo "EXECUTOR_NUMBER :: ${env.EXECUTOR_NUMBER}"
                    echo "NODE_NAME :: ${env.NODE_NAME}"
                    echo "NODE_LABELS :: ${env.NODE_LABELS}"
                    echo "WORKSPACE :: ${env.WORKSPACE}"
                    echo "JENKINS_HOME :: ${env.JENKINS_HOME}"
                    echo "JENKINS_URL :: ${env.JENKINS_URL}"
                    echo "BUILD_URL ::${env.BUILD_URL}"
                    echo "JOB_URL :: ${env.JOB_URL}"
    
                }
            }
      
    stage("Env Variables") {
        steps {
            echo "The build number is ${env.BUILD_NUMBER}"
            echo "You can also use \${BUILD_NUMBER} -> ${BUILD_NUMBER}"
            sh 'echo "I can access $BUILD_NUMBER in shell command as well."'
        }
        
    }
    
    stage("Custom Env Variables") {
        environment {
            NAME = "Alan"
            }

        steps {
            echo "FOO = ${env.FOO}"
            echo "NAME = ${env.NAME}"

            script {
                env.TEST_VARIABLE = "some test value"
             }
            echo "TEST_VARIABLE = ${env.TEST_VARIABLE}"

            withEnv(["ANOTHER_ENV_VAR=here is some value"]) {
                echo "ANOTHER_ENV_VAR = ${env.ANOTHER_ENV_VAR}"
                }
            }
    }
    // Not working
     stage("script Variables") {
         steps {
            //LS = "${sh(script:'ls -lah', returnStdout: true).trim()}"
            // or if you access env variable in the shell command
              sh 'echo $LS'
              sh 'echo $gitCommit'
              sh 'echo $shortCommit'
        }
     }
    
    stage('Test-on-Centos') {
        when { 
            environment name: 'SERVERPLATFORM', value: 'Centos' 
            }
        steps {
            echo 'This will run on Centos'
            ansiColor('xterm') {
            sh 'ansible-playbook -i Ansible-with-Jenkins/hosts Ansible-with-Jenkins/play1.yml'
            //sh 'sh dockerbuild.sh'
            }
        }
    }
    stage('Test-on-Ubuntu') {
        when { 
            environment name: 'SERVERPLATFORM', value: 'Ubuntu' 
            }
        steps {
            echo 'This will run on Ubuntu'
            ansiColor('xterm') {
            sh 'ansible-playbook -i Ansible-with-Jenkins/hosts Ansible-with-Jenkins/play2.yml'
            }
        }
    }

    
    stage('Cleanup') {
        steps {
            echo "This stage only zip the artificates"
            }
    }
        // End of stages

    stage('Confirmation') {
            input {
                message "Should we continue to Print all env variables?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Ajay Kumar', description: 'Who should I say hello to?')
                    choice(name: 'ENV-PRINT', choices: ['Yes', 'No', 'nochange'], description: 'Pick yes to display all')
                }
             }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
                sh 'printenv'
                }
            when { 
                environment name: 'ENV-PRINT', value: 'Yes'
            }

    }
}

    post {
            always {
                echo 'One way or another, I have finished'
                // deleteDir() /* delete the working dir normally workspace */
                //cleanWs() /* clean up workspace */
                //archiveArtifacts artifacts: 'targetbuild-*.zip', followSymlinks: false, onlyIfSuccessful: true
                }
        
            // success {
            //     echo 'Success'
            //     slackSend channel: '#jenkins-builds',
            //     color: 'good',
            //     message: "The pipeline ${currentBuild.fullDisplayName} completed successfully."
            //     }
                  
            // unstable {
            //     echo 'I am unstable :/'
            //     }
        
            failure {
                 mail to: 'ajay011.sharma@hotmail.com',
                 cc: 'macme.tang@gmail.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
                }
            changed {
             echo 'Things were different before...'
                }   
        }
}
